apt:
  base_packages:
    - ca-certificates
    - curl
    - gnupg
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker-compose

lvm:
  device_name: /dev/sda
  volume_group: ubuntu-vg
  logical_volume: ubuntu-lv